# -*- coding: utf-8 -*-
"""TP1-ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pmRfSjyYs-cv2HeNI3OjDdxg4PHrlGm
"""

import numpy as np
vector = np.array([1,2,3,4,5,6])
columv = vector.reshape(-1,1)
print(columv)

#selecting elements
third_element = vector[2]
all_elements = vector[:]
up_to_third = vector[:3]
after_third = vector[3:]
last_element = vector[-1]
print(third_element)
print(all_elements)
print(up_to_third)
print(after_third)
print(last_element)
# Calculating Dot Product
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
dot_product = np.dot(vector_a, vector_b)
print("The dot:",dot_product)
#random values
random_floats = np.random.rand(3)
random_integers = np.random.randint(1, 11, 3)
print('random floats',random_floats)
print('random integers',random_integers)
#creating two dim array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print ('Matrix:',matrix)
#Selecting elements
second_row_second_column = matrix[1, 1]
first_two_rows_all_columns = matrix[:2, :]
all_rows_second_column = matrix[:, 1]
print('1',second_row_second_column)
print('2',first_two_rows_all_columns)
print('3',all_rows_second_column)

# Describing a Matrix
shape = matrix.shape
size = matrix.size
dimensions = matrix.ndim
print('the shape',shape)
print('the size',size)
print('dimensions',dimensions)
# Finding the Maximum and Minimum Values
max_value = np.max(matrix)
min_value = np.min(matrix)
print('max matrix',max_value)
print('min matix',min_value)
max_in_columns = np.max(matrix, axis=0)
max_in_rows = np.max(matrix, axis=1)
print('the max in columns',max_in_columns)
print('the max in rows',max_in_rows)
# Descriptive Statistics
mean_value = np.mean(matrix)
variance = np.var(matrix)
std_deviation = np.std(matrix)
mean_in_columns = np.mean(matrix, axis=0)
# Reshaping Arrays
matrix_4x3 = np.arange(12).reshape(4, 3)
matrix_2x6 = matrix_4x3.reshape(2, 6)
reshape_1 = matrix_4x3.reshape(1,-1)#for computation-here the shape is complete
reshape_2 = matrix_4x3.reshape(12)#the size here is not complte so we can't make computation
print('the first matrix',matrix_4x3)
print('the 2*6',matrix_2x6)
print('reshape1',reshape_1)
print('reshape2',reshape_2)
#transpose
trnspose=reshape_1.T
print('transpose 1',trnspose)
trns=reshape_2.T #does not work here cause In NumPy, transposing a 1D array does nothing. The .T attribute only works when the array has at least two dimensions.

print('t2',trns)
# Flattening a Matrix(we can use reshape also)
flattened_matrix = matrix_4x3.flatten()
print('transformation to 1 array',flattened_matrix)
# Adding and Subtracting Matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
print('matrix1',matrix_a)
print('matrix2',matrix_b)
added_matrices = matrix_a + matrix_b
subtracted_matrices = matrix_a - matrix_b
print('the added matrix ',added_matrices)
print('the subtracted matrix \n',subtracted_matrices)
# Multiplying Matrices
matrix_multiplication = np.dot(matrix_a, matrix_b)
elementwise_multiplication = matrix_a * matrix_b
print('mat_multiplication',matrix_multiplication)
print('elementwise',elementwise_multiplication)